/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1c1b1b",
        "primary-fixed": "#ffe08f",
        "surface-container-highest": "#e2e2e2",
        "surface-container-low": "#f3f3f3",
        "background": "#f9f9f9",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#584400",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary": "#ffffff",
        "tertiary": "#5f5e5e",
        "on-surface-variant": "#4e4632",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-container": "#656464",
        "on-error-container": "#93000a",
        "outline": "#807660",
        "on-surface": "#1a1c1c",
        "outline-variant": "#d2c5ab",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#1b1c1c",
        "tertiary-fixed": "#e4e2e1",
        "surface-container": "#eeeeee",
        "surface": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "error": "#ba1a1a",
        "surface-tint": "#755b00",
        "on-secondary-fixed-variant": "#474646",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#545453",
        "primary": "#755b00",
        "inverse-primary": "#f3c000",
        "primary-container": "#f5c200",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-container-high": "#e8e8e8",
        "on-primary-container": "#685100",
        "surface-bright": "#f9f9f9",
        "tertiary-container": "#cac8c8",
        "on-tertiary-fixed-variant": "#474746",
        "error-container": "#ffdad6",
        "surface-dim": "#dadada",
        "secondary": "#5f5e5e",
        "primary-fixed-dim": "#f3c000",
        "on-background": "#1a1c1c",
        "inverse-surface": "#2f3131",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary-container": "#e5e2e1",
        "on-primary-fixed": "#241a00"
      },
      spacing: {
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "gutter": "32px",
        "section-gap": "120px",
        "stack-lg": "24px",
        "margin-desktop": "80px"
      },
      fontFamily: {
        "body-lg": ["Work Sans", "sans-serif"],
        "headline-lg": ["Barlow Condensed", "sans-serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "display-xl": ["Barlow Condensed", "sans-serif"],
        "headline-md": ["Barlow Condensed", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "headline-sm": ["Barlow Condensed", "sans-serif"],
        "label-bold": ["Work Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
